import Typography from "components/atoms/Typography";
import type { NextPage } from "next";
import Head from "next/head";
import { Header } from "components/organisms/Header";
import Link from "next/link";
import { Linkedin as LinkedinIcon, GitHub as GitHubIcon } from "react-feather";

const technologies = [
  "React.js",
  "Next.js",
  "Typescript",
  "Tailwind",
  "CSS Modules",
];

const Home: NextPage = () => (
  <>
    <Head>
      <title>Luka Ušalj - Senior Frontend Developer</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className="h-screen flex flex-col justify-between">
      <div>
        <Header />
        <div className="pb-0 p-8 md:p-14 md:mt-4 flex flex-col md:flex-row justify-between">
          <div className="md:w-2/3">
            <Typography variant="h1">Senior Frontend Developer</Typography>
            <Typography variant="p" className="sm:pr-12">
              I'm experienced in building web apps from scratch in fast paced
              agile environments. Currently re-engineering{" "}
              <Link href="curio.io">
                <a className="underline decoration-pink-500 decoration-2 underline-offset-2">
                  curio.io
                </a>
              </Link>
            </Typography>
          </div>
          <div className="hidden md:mt-4 md:w-1/3 md:flex md:flex-col md:items-end">
            {technologies.map((technology) => (
              <Typography
                key={technology}
                variant="h5"
                as="h2"
                noMargin
                noLeading
                className="text-slate-300 my-1"
              >
                {technology}
              </Typography>
            ))}
          </div>
        </div>
      </div>
      <footer className="p-14 md:p-14 flex flex-col items-center gap-5">
        <Typography variant="xs">
          <a
            className="hover:underline decoration-pink-500 underline-offset-2"
            href="mailto:luka.usalj@gmail.com"
          >
            luka.usalj@gmail.com
          </a>
        </Typography>

        <div className="flex gap-4">
          <Link href="https://www.linkedin.com/in/lukausalj/">
            <a target="_blank">
              <LinkedinIcon />
            </a>
          </Link>
          <Link href="https://github.com/lusa9">
            <a target="_blank">
              <GitHubIcon />
            </a>
          </Link>
        </div>
      </footer>
    </div>
  </>
);

export default Home;
