import { NavLink } from "components/molecules/NavLink";
import Typography from "components/atoms/Typography";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useMemo } from "react";
import styles from "../styles/Home.module.css";
import { Navigation } from "components/organisms/Navigation";
import { Header } from "components/organisms/Header";

const Home: NextPage = () => {
  return (
    <div className="p-4">
      <Head>
        <title>Luka Ušalj - Senior Frontend Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Typography variant="h1">
        Luka Ušalj
        <br />
        Senior Frontend Developer
      </Typography>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
